version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      BOT_TOKEN: "8401609959:AAFGmYh29uJM-JJNUMJc0ByKVfDfQSlILMc"
      ADMIN_ID: "1702919355"
      CH1: "@bigbumpersaleoffers"
      CH1_LINK: "https://t.me/bigbumpersaleoffers"
      CH2: "@backupchannelbum"
      CH2_LINK: "https://t.me/backupchannelbum"
      CONTACT_LINK: "https://t.me/rk_production_house"
      WEBHOOK_SECRET: "dev-secret"
    volumes:
      - .:/var/www/html